name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm run build

      - name: publish walrus-did-resolver package
        uses: JS-DevTools/npm-publish@v3
        id: walrus-did-resolver
        with:
            access: public
            provenance: true
            token: ${{ secrets.NPM_TOKEN }}
            package: "packages/walrus-did-resolver/package.json"
            strategy: upgrade

      - name: publish walrus-did package
        uses: JS-DevTools/npm-publish@v3
        id: walrus-did
        with:
            access: public
            provenance: true
            token: ${{ secrets.NPM_TOKEN }}
            package: "packages/walrus-did/package.json"
            strategy: upgrade
